### ISSUE TITLE
 missing option to create json as a tree

### ISSUE THREAD

**Issue by mehimanshupatil** [ryanpcmcquen/propertiesToJSON#4]
If properties are like follow
```
a.b=c
a.d=e
```
then output should be
```
{
  "a": {
    "b": "c",
    "d": "e"
  }
}
```
instead of 
```
{
  "a.b": "c",
  "a.d": "e"
}
```

**Comment by ryanpcmcquen** [comment]
Is that a syntax used in properties files?

**Comment by mehimanshupatil** [comment]
Though properties specs don't mention dots in key. It's a common convention used to segregate common properties like it is used in spring.

**Comment by ryanpcmcquen** [comment]
This library shouldn't extend the spec syntax.

**Comment by mehimanshupatil** [comment]
Ok, you can close the issue. I have implemented the same. if you want to incorporate I can add a PR request.

**Comment by ryanpcmcquen** [comment]
Send it over and I will take a look.
